title: "Cyrill Rafael Vasilyev"
description: "Artwork showcase"

url: "https://cyrillrafael.org"  # Full URL with https if needed
baseurl: ""                     # Important for GitHub Pages on a user site

# Permalinks
permalink: "/:title/"

# Navigation links
nav_links:
  - title: "Paintings"
    url: "/paintings"
  - title: "Linocuts"
    url: "/linocuts"
  - title: "About"
    url: "/about"
  - title: "CV"
    url: "/cv"
  - title: "Instagram"
    url: "https://www.instagram.com/cyrillrafael/"
    icon: "fab fa-instagram"
  - title: "Telegram"
    url: "https://t.me/+31686218199/"
    icon: "fab fa-telegram"
  - title: "Installations"
    url: "/installations/"

# Exclude unnecessary files from Jekyll processing
exclude:
  - .git
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - _site
  - vendor
  - node_modules
  
include:
  - installation2025

# Redirects (if you actually want to redirect your homepage)
redirects:
  - from: "/"
    to: "/paintings/"
